version: '2'

services:
  hatu:
    build: .
    volumes:
      - ./client:/hatu/client
      - ./server:/hatu/server
      - ./config:/hatu/config
      - /hatu/node_modules
      - ./package.json:/hatu/package.json
      - ./.babelrc:/hatu/.babelrc
#  Since the editor may delete the original file and create a new one, the mount might be broken.
#  You may need to restart the service to synchronize the package.json and .babelrc

    volumes_from:
      - slice
    depends_on:
      - dvid
    ports:
      - 2222:2222

  slice:
    image: "hjwissac/slice15"
    volumes:
      - /image

  dvid:
    image: "flyem/dvid"
    ports:
      - 8000:8000

networks:
  default: